# Generated by Django 4.2.11 on 2026-01-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(help_text='Unique name of the tenant/organization', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the tenant', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is currently active')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for the tenant', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration settings')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx')],
            },
        ),
    ]
