# Generated by Django 4.2.11 on 2026-01-18 13:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('patient_id', models.CharField(help_text='Unique patient identifier within the tenant', max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('code', models.CharField(help_text='Unique test type code within tenant', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(help_text='Category of test (e.g., Blood Test, Urine Test, etc.)', max_length=100)),
                ('normal_range', models.CharField(blank=True, help_text='Normal range for test results', max_length=255, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Unit of measurement (e.g., mg/dL, mmol/L)', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the test', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_duration_hours', models.IntegerField(help_text='Estimated time to complete test in hours', validators=[django.core.validators.MinValueValidator(1)])),
                ('requires_sample', models.BooleanField(default=True, help_text='Whether this test requires a physical sample')),
                ('sample_type', models.CharField(blank=True, help_text='Type of sample required (e.g., Blood, Urine, Tissue)', max_length=100, null=True)),
                ('sample_volume_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Required sample volume in milliliters', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Test Type',
                'verbose_name_plural': 'Test Types',
                'db_table': 'test_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('test_number', models.CharField(help_text='Unique test number within tenant', max_length=50)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Scheduled date for test', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when test was completed', null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical notes or reason for test', null=True)),
                ('result_value', models.CharField(blank=True, help_text='Test result value', max_length=255, null=True)),
                ('result_interpretation', models.TextField(blank=True, help_text='Interpretation of results', null=True)),
                ('is_abnormal', models.BooleanField(default=False, help_text='Flag for abnormal results')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date and time of review', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordered_by', models.ForeignKey(help_text='User who ordered this test', on_delete=django.db.models.deletion.PROTECT, related_name='ordered_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='patients.testtype')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'tests',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('sample_id', models.CharField(help_text='Unique sample identifier within tenant', max_length=50)),
                ('sample_type', models.CharField(help_text='Type of sample (Blood, Urine, Tissue, etc.)', max_length=100)),
                ('volume_ml', models.DecimalField(decimal_places=2, help_text='Sample volume in milliliters', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('collected_at', models.DateTimeField()),
                ('collection_method', models.CharField(blank=True, help_text='Method used for collection', max_length=255, null=True)),
                ('collection_site', models.CharField(blank=True, help_text='Anatomical site of collection', max_length=255, null=True)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('in_transit', 'In Transit'), ('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('discarded', 'Discarded')], default='collected', max_length=20)),
                ('storage_location', models.CharField(blank=True, help_text='Current storage location', max_length=255, null=True)),
                ('storage_temperature', models.CharField(blank=True, help_text='Required storage temperature', max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('quality_acceptable', models.BooleanField(default=True, help_text='Whether sample quality is acceptable for testing')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for sample rejection', null=True)),
                ('is_hazardous', models.BooleanField(default=False, help_text='Flag for hazardous samples')),
                ('special_handling_instructions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_samples', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_samples', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this record', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='patients.test')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
                'db_table': 'samples',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testtype',
            index=models.Index(fields=['tenant', 'code'], name='test_types_tenant__00fb41_idx'),
        ),
        migrations.AddIndex(
            model_name='testtype',
            index=models.Index(fields=['tenant', 'category'], name='test_types_tenant__bbb6d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='testtype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_test_type_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['tenant', 'test_number'], name='tests_tenant__5c7f10_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['tenant', 'patient', 'status'], name='tests_tenant__7dee71_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['tenant', 'status', 'ordered_at'], name='tests_tenant__4d28d7_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['tenant', 'test_type'], name='tests_tenant__9dfdca_idx'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('tenant', 'test_number'), name='unique_test_number_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['tenant', 'sample_id'], name='samples_tenant__9cc7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['tenant', 'test', 'status'], name='samples_tenant__734e60_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['tenant', 'status', 'collected_at'], name='samples_tenant__f9127b_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('tenant', 'sample_id'), name='unique_sample_id_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'patient_id'], name='patients_tenant__2b113d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='patients_tenant__5684e3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'is_active'], name='patients_tenant__551a31_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('tenant', 'patient_id'), name='unique_patient_id_per_tenant'),
        ),
    ]
